### ISSUE TITLE
how to build it

### ISSUE THREAD

**Issue by germe-fur** [sakhnik/neovim-vala#1]
there is not information about how to compile or execute the program/app so...
how i can run the project?

**Comment by sakhnik** [comment]
I'm sorry, I'm abandoning the project in favour of [neovim-sdl2](http://github.com/sakhnik/neovim-sdl2).
If you'd like to build it or even take it over, you could take a peek at [build.sh](https://github.com/sakhnik/neovim-vala/blob/main/scripts/build.sh). That's how I built it in MinGW.
